### PR TITLE
CIL race condition detection support 

### PR DESCRIPTION
**Pull request by xi-liu-ds**
This PR adds race condition detection support on CIL backed languages, such as .NET platform languages.

We will add unit tests later since we are still fine tunning Infer# translation module.

### CODE REVIEW

**Review by ngorogiannis — COMMENTED** [review]
Hi! This change looks unrelated to the thread safety work, do you mind separating it into another PR?

**Comment by xi-liu-ds** [comment]
> Hi! This change looks unrelated to the thread safety work, do you mind separating it into another PR?

Could you be a little bit more specific which change you are mentioning? Thanks!

**Comment by ngorogiannis** [comment]
Ah sorry I thought the UI will attach my comment on the commit I was viewing :) 

I meant 942b7ae, the commit about resource leaks.

**Comment by xi-liu-ds** [comment]
> Ah sorry I thought the UI will attach my comment on the commit I was viewing :)
> 
> I meant [942b7ae](https://github.com/facebook/infer/commit/942b7aea35f8c19d786232ca48830ddc0591c29d), the commit about resource leaks.

Sure! Done.

**Comment by xi-liu-ds** [comment]
Looks like there are some unit test failure. Is there anything I can do from my side? Thanks!

**Comment by ngorogiannis** [comment]
> Looks like there are some unit test failure. Is there anything I can do from my side? Thanks!

No problem, it's just a formatter issue, I'll fix it.

**Pull request closed without merging**
