### PR TITLE
use sudo to run the linux script

### PR DESCRIPTION
**Pull request by mauryat**

### CODE REVIEW

**Comment by jvillard** [comment]
Sorry for the late reply. Can you say more about why the script should be run as root?

**Comment by jeremydubreil** [comment]
@mauryat, any update on why you need to the script to run as root?

**Comment by mauryat** [comment]
@jeremydubreil , sorry I've not had a chance to look at it again as this was a long time ago. But, from what I remember, Ubuntu Linux required sudo permission to be able to run the script.

**Comment by jvillard** [comment]
Let's reopen this once we find out why/when using `sudo` is needed.

**Pull request closed without merging**
