### PR TITLE
Documentation Update for Infer project

### PR DESCRIPTION
**Pull request by roshankcjha**
Please see [CONTRIBUTING.md](./CONTRIBUTING.md) for how to set up your development environment and run tests.
Changes made to the Readme.md (organised the content for making contributions)
Added Security.md file as well.

### CODE REVIEW

**Comment by roshankcjha** [comment]
@ngorogiannis  @dulmarod @roro47 do checkout this pull request and provide valuable updates.

**Comment by roshankcjha** [comment]
@jvillard  and other maintainers do have a look at this pull request and provide valuable suggestions

**Comment by jvillard** [comment]
Hey @roshankcjha, there's no need to tag individual contributors to review your PR, we all get GitHub notifications by email. Of course please feel free to "ping" your PR if no one has answered in a few days.

**Comment by jvillard** [comment]
I don't think this can be merged as we don't want this security policy. These decisions are delicate to make so suggesting new policies should be carefully motivated. The rest of the PR seems not particularly relevant to infer either. Closing for now but do feel free to re-open with a more targeted PR and some motivation for the changes.

**Pull request closed without merging**
