### PR TITLE
fix(docs): Update README.md

### PR DESCRIPTION
**Pull request by iamdarshshah**
### Changes

- [x] Aligning header elements to the center. 
- [x] Added logo 

> This makes the docs look symmetrical and looks a bit catchy.

### CODE REVIEW

**Comment by jvillard** [comment]
I think it's better for maintainability to keep the markdown format here.

**Comment by iamdarshshah** [comment]
Yes, agreed. But if we consider accessibility, then using `tags` will be beneficial. Apart from it, if you still want to go with markdown format, that's fine will update it to the original one and will add a logo to it.

Would that be good?

Thanks @jvillard 👍

**Comment by jvillard** [comment]
Sorry, what do you mean by using tags?

Also note that the logo is available in the repo so you could use this instead of a link to fbinfer.com: https://github.com/facebook/infer/blob/master/website/static/img/logo.png

Not sure how snazzy we want to make this README though, there's already the website for the pretty-looking pages :)

**Comment by iamdarshshah** [comment]
> Sorry, what do you mean by using tags?

By `tags`, I mean `HTML` tags which we can use for providing `Heading` to the document.

> Also note that the logo is available in the repo so you could use this instead of a link to fbinfer.com: https://github.com/facebook/infer/blob/master/website/static/img/logo.png

Sure, will update this

> Not sure how snazzy we want to make this README though, there's already the website for the pretty-looking pages :)

Totally agreed with this point. The website is really good but with that if we can make the GitHub documentation i.e., readme.md  for this project looks better then it will be good for the one who is checking this project for the first time and that too by visiting GitHub repo.

**Comment by jvillard** [comment]
Can you elaborate why tags would be better for accessibility? In the final page the markdown is rendered as the appropriate html tags already, eg `# Infer` becomes `<h1>Infer</h1>`. I don't think html tags are desirable here.

**Comment by iamdarshshah** [comment]
Agreed with your point. If you think html tags are not desirable here or better for maintainability we should avoid using html here, then will update it (this will make it aligned header elements to the left). But will keep the logo as of now.

Thanks @jvillard 👍

**Comment by surajkumar8642** [comment]
I use this fast time.

**Pull request closed without merging**
