### PR TITLE
CodeAI uses Infer under the hood to find bugs.

### PR DESCRIPTION
**Pull request by benjaminbales**
CodeAI sifts through false positives in the results using its proprietary AI technology.  In addition, it suggests simple defensive coding fixes based information parsed from the output of Infer.

### CODE REVIEW

**Comment by jvillard** [comment]
Hi @benjaminbales, many thanks for your PR. Are you able to sign the CLA so we can incorporate it into our website?

**Comment by benjaminbales** [comment]
of course.  Where can I find the CLA?

**Comment by benjaminbales** [comment]
I just signed it.  Sorry for the delay.

**Comment by jvillard** [comment]
Thanks again!

**Pull request merged**
