### PR TITLE
docker image

### PR DESCRIPTION
**Pull request by DoctorQ**
I make a infer's image by docker tech,please check it.

### CODE REVIEW

**Comment by DoctorQ** [comment]
@facebook-github-bot  Done it.

**Comment by wielkapala** [comment]
it my pleasure end it i thanks for this object that big corporation

**Comment by jvillard** [comment]
Hi @DoctorQ, could you tell me a bit more about how you envision that people will use this docker image? Thanks!

**Comment by iainsmith** [comment]
Hey @jvillard. I was just looking for a docker image, so I thought I would share my use case.

* I want to try infer for the first time and running a docker image is a single command. (Only helps people already familiar with docker, but that's a growing number of people.)
* I want to spin up a VPS for CI that can run infer & act as a git remote. Building this on docker, makes it portable and sharable. 
* Running through docker means I can run infer independently of my own environment.

**Pull request closed without merging**
