### PR TITLE
Remove explicit return of unit and use ignore instead

### PR DESCRIPTION
**Pull request by xennygrimmato**
Instead of returning `()` explicitly, use `ignore (f x)` to ignore whatever is returned by `f` and return `()`.

### CODE REVIEW

**Comment by jvillard** [comment]
Please make this just one commit instead of four.

**Comment by jberdine** [comment]
Tagging to clarify that this PR needs to be updated before we can proceed with it.

**Comment by my3190** [comment]
master xennygrimmato

**Comment by cristianoc** [comment]
The file was unused and has been deleted, closing this.

**Pull request closed without merging**
