### PR TITLE
Add documentation for some IR and backend modules

### PR DESCRIPTION
**Pull request by xennygrimmato**
- Brief description of modules and some functions provided by them

### CODE REVIEW

**Comment by cristianoc** [comment]
@jberdine @jvillard do we have a Makefile target to generate ocamldoc from the code?
Just wondering what should go in .mli/.rei files directly vs in README.md files.

**Comment by jberdine** [comment]
Last time I tried, ocamldoc fell over on infer.  It was a while ago though.  Still, the documentation comments can sometimes be shown by merlin (like show type, but show the doc comment) using merlin-document in emacs or however other editors expose it.  The doc comments also can be shown in the auto-completion pop-ups.  So I would say to take at least that perspective: put documentation at the level of single functions in doc comments in .mli/.rei, and higher-level or broader scope information could go elsewhere.  Although info that is specific to a file might best be a comment in that file.

**Comment by xennygrimmato** [comment]
So, should I add comments to source files instead of Readme files to continue with this?

**Comment by cristianoc** [comment]
@xennygrimmato yes I think that's better.
There's value, in the README, to explain what the concepts and parts are: there's a call graph, there's a control-flow graph, perhaps what their main function is, big picture kind of description. But for the details of each module, especially those details that are likely to need to be maintained when those modules evolve over time, it's best to have comments in the source files.

**Comment by jberdine** [comment]
Tagging to clarify that this PR needs to be updated before we can proceed with it.

**Comment by jeremydubreil** [comment]
Any update on this?

**Comment by jvillard** [comment]
The implementation has diverged from the documentation in this PR so closing for now. Do feel free to re-open with an updated version.

**Pull request closed without merging**
