### PR TITLE
add wolfSSL to list of users that are testing with Infer

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**
add wolfSSL to list of users that are testing with Infer

### CODE REVIEW

**Comment by TomMD** [comment]
@JacobBarthelmeh Neat!  I was looking at how well Infer performed on WolfSSL because I was going to ask if they wanted to run it on CI.  In my explorations ([here](https://console.muse.dev/result/TomMD/wolfssl/01ES0HGBKG599YV5VCGK79XJBM?all=Infer)) I didn't see a "silver bullet" bug that would have been compelling to present to WolfSSL as an introduction to Infer.

If you don't mind me asking, what was the convincing point at which WolfSSL decided to start using Infer?

**Comment by JacobBarthelmeh** [comment]
Hi @TomMD I looked at the Muse Console linked, thanks for that, it is interesting to see some of the other tools listed there also. Sorry, I do not know for sure what the initial convincing point internally was for the decision to use Infer. We have been using it for some time though to help assist with catching issues before they make it into a release.

~jacob

**Comment by jvillard** [comment]
This is great news, thanks for the PR! @JacobBarthelmeh are you able to sign the CLA? I can also just push the same change to the website myself if that's complicated.

**Comment by JacobBarthelmeh** [comment]
Hi @jvillard please make the change directly to the website and close this out. Thanks for the Infer tool and the work you guys do! As a side note we have a link back to the Infer site on our testing page here (https://www.wolfssl.com/overview-of-testing-in-wolfssl/).

~jacob

**Pull request closed without merging**
