### PR TITLE
Perform tests within CI testing

### PR DESCRIPTION
**Pull request by yakobowski**
This PR updates the github action to actually perform Infer's testing within the action.

The first three commits add the required dependencies (utop and ocamlformat), and add a infer-tests.opam file. The fourth commit activates the testing per se.

### CODE REVIEW

**Comment by yakobowski** [comment]
Note: I have tried updating the ocaml caching action to the supported version (https://github.com/ocaml/setup-ocaml) in https://github.com/yakobowski/infer/commit/19290d07fba2c50acbfd2351df4aaf25c3d8d243. It seems to make things worse: Infer's dependencies are no longer cached, only opam and the compiler are. This is documented as being the expected behavior, so I decided to keep the initial action.

**Comment by yakobowski** [comment]
The action fails on MacOS, but works on my own repo: https://github.com/yakobowski/infer/runs/4257316364. Not sure what is happening here.

**Comment by yakobowski** [comment]
Actually could you try restarting the MacOS testing (I don't have enough rights myself). The build cache should have expired in the meantime, and a restart could help. Otherwise I don't see anything I can fix myself :(

**Comment by yakobowski** [comment]
It worked!! 🎉

**Comment by jvillard** [comment]
Thanks for improving the GitHub CI for everyone, @yakobowski!

**Pull request closed without merging**
