### PR TITLE
Update supported opam version to 1.2.2

### LINKED ISSUE #588: build-infer.sh fails with opam 1.2.0
Related to #554 (specifically this https://github.com/facebook/infer/pull/554#issuecomment-271283944)

Confirm that build-infer.sh fails on opam 1.2.0 due to the changed name of the flag as of https://github.com/ocaml/opam/commit/9ccabc03f75b1908ce5fda4c676ddd16d9d0c7ce#diff-906c973c07f8c64e8dd7866de2b40e35. Error is:
```
initializing opam... 
opam: unknown option `--compiler'
```

Would either need to support both `--comp` and `--compiler` flags in build-infer.sh so Debian stable continues to work, or increase minimum opam version to 1.2.1 in [INSTALL.md](https://github.com/facebook/infer/blob/master/INSTALL.md)

### PR DESCRIPTION
**Pull request by 3flex**
Fixes #588

### CODE REVIEW

**Comment by jvillard** [comment]
As discussed in #588, can you update this so that it bumps the minimum required version in the instructions instead? Thanks!

**Comment by 3flex** [comment]
Version 1.2.1 or 1.2.2? Not really sure what the difference is but either one would fix at least the `--comp`/`--compiler` discrepancy

**Comment by 3flex** [comment]
Oh and also with opam 2 in beta, and presumably untested by Infer package process, 1.2.x would the only supported version for now?

**Comment by 3flex** [comment]
Updated, assuming 1.2.2 should be the only supported version for now.

**Comment by jvillard** [comment]
Looks good, thanks!

**Pull request closed without merging**
